POST http://localhost:3333/orders
Content-Type: application/json

{
  "total": 20,
  "products": [
    {
      "product_id": "a014dcb7-a36d-4376-97d2-f319fe14690e",
      "price": 10,
      "quantity": 2
    }
  ],
  "coupon_id": "",
  "store_id": "b2810065-bd1d-4a10-a8df-f5cd7f798683",
  "payment_method": "eced01fb-3db6-4e9a-be81-1969609fe060"
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name": "Rafa Tedesco",
    "email": "tedesco@mail.com",
    "password": "1234Abc##",
    "cpf": "74282559020",
    "phone": "1298721723"
}

###

POST http://localhost:3001/api/users/login
Content-Type: application/json

{
	"email": "tedesco@mail.com",
	"password": "1234Abc##"
}

###

GET http://localhost:3001/api/stores/b2810065-bd1d-4a10-a8df-f5cd7f798683
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM4NDczMWExLWFiNDktNDQ4YS04MDc2LThhYWEzMDg1NjgzMSIsInJvbGUiOiJ1c2VyIiwibmFtZSI6IlJhZmEgVGVkZXNjbyIsImlhdCI6MTcwNDU1MDA2NywiZXhwIjoxNzA0NjM2NDY3fQ.7TicNnUuq2dyXTkJtUh2TAe5od98o5Ufn0dC9JSHgfw

###

GET http://localhost:3001/api/products

###

POST http://localhost:3001/api/stores/f0d4210f-86ac-4fc6-b780-43f20de1ff4a/products 
content-type: application/json

{
    "name": "pizza",
    "description": "tasty pizza",
    "price": 30,
    "quantity": 1,
    "promotionPrice": 28,
    "categoryId": "3cb5ea67-66a5-49c0-a2a2-a86c8c2b9b37"
}